
    Vagrant.configure("2") do |config|
        config.vm.boot_timeout = 500
        # Master node
        config.vm.define "master" do |node|
            node.vm.box = "bento/ubuntu-24.04"
            node.vm.hostname = "master"
            node.vm.network :private_network, ip: "192.168.59.50"
            node.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"

            node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
            node.vm.provision "shell", inline: <<-SHELL
                sudo cp /vagrant/hosts /etc/hosts
                sudo apt-get update
                sudo apt-get install -y ansible sshpass
            SHELL


            node.vm.provider :libvirt do |libvirt|
                libvirt.memory = 1024
                libvirt.cpus = 1
            end
        end
    
        config.vm.define "node1" do |node| 
            node.vm.hostname = "node1"
            node.vm.box = "bento/ubuntu-24.04"
            node.vm.network :private_network, ip: "192.168.59.51"
            node.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
            node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
            node.vm.provision "shell", inline: <<-SHELL
                sudo cp /vagrant/hosts /etc/hosts
                SHELL
            node.vm.provider :libvirt do |libvirt|
                libvirt.memory = 1024
                libvirt.cpus = 1
            end
        end
    
        config.vm.define "node2" do |node| 
            node.vm.hostname = "node2"
            node.vm.box = "bento/ubuntu-24.04"
            node.vm.network :private_network, ip: "192.168.59.52"
            node.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
            node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
            node.vm.provision "shell", inline: <<-SHELL
                sudo cp /vagrant/hosts /etc/hosts
                SHELL
            node.vm.provider :libvirt do |libvirt|
                libvirt.memory = 1024
                libvirt.cpus = 1
            end
        end
    
    end
    