Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 500

  # Master node
  config.vm.define "master" do |node|
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.59.50"
    node.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"

    node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
    node.vm.synced_folder "../ansible", "/etc/ansible", type: "9p", disabled: false
    node.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/hosts /etc/hosts
      sudo apt-get update
      sudo apt-get install -y ansible sshpass
    SHELL


    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end
  # Node1
  config.vm.define "node1" do |node| 
    node.vm.hostname = "node1"
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.network :private_network, ip: "192.168.59.51"
    node.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"

    node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
    node.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/hosts /etc/hosts
    SHELL

    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end
  # Node2
  config.vm.define "node2" do |node| 
    node.vm.hostname = "node2"
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.network :private_network, ip: "192.168.59.52"
    node.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"

    node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
    node.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/hosts /etc/hosts
    SHELL

    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end
  # Node3
  config.vm.define "node3" do |node| 
    node.vm.hostname = "node3"
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.network :private_network, ip: "192.168.59.53"
    node.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"

    node.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false
    node.vm.provision "shell", inline: <<-SHELL
      sudo cp /vagrant/hosts /etc/hosts
    SHELL

    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end
  # Node8 Centos
  config.vm.define "node8" do |node|
    node.vm.box = "generic/centos8"
    node.vm.hostname = "node8"
    
    node.vm.network :private_network, ip: "192.168.59.58"
    node.vm.network "forwarded_port", guest: 22, host: 2208, id: "ssh"

    set_up_network = File.read("tools/vagrant_rhel_network_set_up.sh")
    node.vm.provision "shell", inline: set_up_network, args: ["192.168.59.58","2208"], privileged: true

    hosts = File.read("hosts")
    node.vm.provision "shell", inline: <<-SHELL
      echo "192.168.59.50 master" >> /etc/hosts
      echo "192.168.59.51 node1" >> /etc/hosts
      echo "192.168.59.52 node2" >> /etc/hosts
      echo "192.168.59.53 node3" >> /etc/hosts
      echo "192.168.59.58 node8" >> /etc/hosts
      echo "192.168.59.59 node9" >> /etc/hosts
    SHELL
      
    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end

  # Node9 Centos
  config.vm.define "node9" do |node|
    node.vm.box = "generic/centos8"
    node.vm.hostname = "node9"
    
    node.vm.network :private_network, ip: "192.168.59.59"
    node.vm.network "forwarded_port", guest: 22, host: 2208, id: "ssh"

    set_up_network = File.read("tools/vagrant_rhel_network_set_up.sh")
    node.vm.provision "shell", inline: set_up_network, args: ["192.168.59.59","2209"], privileged: true

    hosts = File.read("hosts")
    node.vm.provision "shell", inline: <<-SHELL
      echo "192.168.59.50 master" >> /etc/hosts
      echo "192.168.59.51 node1" >> /etc/hosts
      echo "192.168.59.52 node2" >> /etc/hosts
      echo "192.168.59.53 node3" >> /etc/hosts
      echo "192.168.59.58 node8" >> /etc/hosts
      echo "192.168.59.59 node9" >> /etc/hosts
    SHELL
      
    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
  end
end
