- hosts: web_servers
  become: true
  pre_tasks:
    - name: updates (CentsOS)
      tags: alwaye
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"
    - name: update (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
- hosts: web_servers
  become: true
  roles:
    - web_servers
- hosts: db_servers
  become: true
  roles:
    - db_servers
