- hosts: web_servers
  become: true
  pre_tasks:
    - name: updates (CentsOS)
      tags: alwaye
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"
    - name: update (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
  tasks:
    - name: Install Nginx (Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: Install Ngnix (CentOS)
      ansible.builtin.yum:
        name:
          - yum-utils
          - nginx
      when: ansible_distribution == "CentOS"
    - name: start and enable apache
      tags: apache,centos,httpd
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
